# Generated by Django 6.0.4 on 2026-05-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='size_type',
            field=models.CharField(choices=[('bottom', 'Bas (XS/S/M/L/XL)'), ('top', 'Haut (85B/90C...)'), ('unique', 'Taille unique')], default='bottom', max_length=10),
        ),
    ]
