# Generated by Django 6.0.4 on 2026-05-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Espèces à la livraison'), ('card', 'Carte bancaire'), ('mobile', 'Mobile Money')], default='cash', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='unpaid', max_length=20),
        ),
    ]
