# Generated by Django 6.0.4 on 2026-09-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Espèces à la livraison'), ('online', 'Paiement en ligne (Mobile Money / Carte) — PayDunya')], default='cash', max_length=10),
        ),
    ]
